### ISSUE TITLE
Move libp2p-websocket-star-signal into it's own repo?

### ISSUE THREAD

**Issue by mkg20001** [libp2p/js-libp2p-websocket-star#11]
Good idea / bad idea?

Pros:
 - Easier to manage

Cons:
 - src/utils.js is shared and should be updated simultaneously. 

Edit: The reason why they are separate is because hapi and socket.io (server) add a lot of unnecessary packages

**Comment by diasdavid** [comment]
Note: websocket-star doesn't do signalling, it is actually relaying packets

The ideal plan is to actually do the relaying through a libp2p node as a mounted protocol so that instead of _just one_ rendezvous point we have multiple because any node in the network could become it. This will become trivial to do once Circuit Relay is done.

**Comment by diasdavid** [comment]
it's happening :) https://github.com/libp2p/js-libp2p-websocket-star-rendezvous/pull/1
