### ISSUE TITLE
Use id from multiaddr

### ISSUE THREAD

**Issue by diasdavid** [libp2p/js-libp2p-websocket-star#17]
From the README https://github.com/libp2p/js-libp2p-websocket-star#example
```
// TODO -> review why the ID can not be passed by the .listen call
const ws = new WSStar({ id: id }) // the id is required for the crypto challenge
```

Why shouldn't it use the the id that comes with the multiaddr?

**Comment by mkg20001** [comment]
Because the listener is supposed to listen on the multiaddr it's given.
Imagine you pass in the wrong multiaddr with a different id and it's magically listening on the "actual id". That's confusing.

Maybe not for this issue but: I think we should just drop the multiaddrs entierly and identify the peers using the id. But this would remove the ability for the transport to be used without an id. Related #13

**Comment by mkg20001** [comment]
Oh wait. I misread the whole thing.
The multiaddr does not give the module the private key that is needed for the cryptoChallenge that's soon documented.
