### ISSUE TITLE
Move away from sio. Use libp2p & protobuf instead

### ISSUE THREAD

**Issue by mkg20001** [libp2p/js-libp2p-websocket-star#41]
As @lgierth requested I'm rewriting ws-star to use libp2p and protocol buffers instead of socket.io

Initial draft of the new protocol: [Protocol Draft.md.txt](https://github.com/libp2p/js-libp2p-websocket-star/files/1626456/Protocol.Draft.txt)

**Comment by mkg20001** [comment]
Or wait... should use p2p-circuit instead *facepalm*

**Comment by dryajov** [comment]
mm... not sure where p2p-circuit fits here :), would you mind providing some background?

**Comment by diasdavid** [comment]
@mkg20001 💯 to move away from SIO and to use p2p-circuit.

To make it happen, we will need first to do https://github.com/libp2p/js-libp2p/issues/130 //cc @pgte. Otherwise, the internal wiring will be super messy.

While at that giant refactor, we should also do https://github.com/libp2p/js-libp2p/issues/98 as it will make some of the issues we have detected in the past disappear.

**Comment by mkg20001** [comment]
@dryajov It's about https://github.com/libp2p/js-libp2p/issues/134

**Comment by mkg20001** [comment]
Pr #43

**Comment by mkg20001** [comment]
Closing this as the rendezvous protocol is now a thing. https://github.com/libp2p/js-libp2p-rendezvous
